// GENERATED by dev/requirements/gate/coverage-gate.mjs --write. Do not edit.
// Dart cannot discover case files at runtime, so this list is what the runner
// executes; the gate fails when it and cases/ disagree.

import '../shared/requirement_case.dart';
import 'cases/card-footnotes.4.5.case.dart';
import 'cases/card-states.4.2.case.dart';
import 'cases/countdown-neutral.2.5.case.dart';
import 'cases/countdown-over.2.7.case.dart';
import 'cases/countdown-warning.2.6.case.dart';
import 'cases/current-joke.3.1.case.dart';
import 'cases/elapsed-and-planned.2.4.case.dart';
import 'cases/empty-stage.3.5.case.dart';
import 'cases/joke-optional-text.3.4.case.dart';
import 'cases/joke-run-time.3.2.case.dart';
import 'cases/laugh-strip-dim.3.7.case.dart';
import 'cases/laugh-strip-lit.3.6.case.dart';
import 'cases/one-screen.2.1.case.dart';
import 'cases/pacing-bar.2.9.case.dart';
import 'cases/recording-indicator.2.2.case.dart';
import 'cases/set-list-grid.4.1.case.dart';
import 'cases/setup-highlight.3.3.case.dart';
import 'cases/started-tally.4.4.case.dart';
import 'cases/state-key.4.3.case.dart';
import 'cases/venue-line.2.3.case.dart';

final screenCases = <RequirementCase>[
  cardFootnotes_4_5,
  cardStates_4_2,
  countdownNeutral_2_5,
  countdownOver_2_7,
  countdownWarning_2_6,
  currentJoke_3_1,
  elapsedAndPlanned_2_4,
  emptyStage_3_5,
  jokeOptionalText_3_4,
  jokeRunTime_3_2,
  laughStripDim_3_7,
  laughStripLit_3_6,
  oneScreen_2_1,
  pacingBar_2_9,
  recordingIndicator_2_2,
  setListGrid_4_1,
  setupHighlight_3_3,
  startedTally_4_4,
  stateKey_4_3,
  venueLine_2_3,
];
