// GENERATED by dev/requirements/gate/coverage-gate.mjs --write. Do not edit.
// Dart cannot discover case files at runtime, so this list is what the runner
// executes; the gate fails when it and cases/ disagree.

import '../shared/requirement_case.dart';
import 'cases/app-declarations.8.4.case.dart';
import 'cases/audience-descriptors.1.5.case.dart';
import 'cases/countdown-tone.2.8.case.dart';
import 'cases/joke-fields.1.1.case.dart';
import 'cases/laugh-event-fields.6.3.case.dart';
import 'cases/manual-provenance.5.7.case.dart';
import 'cases/no-laugh-scores-on-stage.4.6.case.dart';
import 'cases/one-capture-clock.6.4.case.dart';
import 'cases/planned-length.1.4.case.dart';
import 'cases/segment-mode-availability.5.2.case.dart';
import 'cases/set-order.1.3.case.dart';
import 'cases/setup-spans.1.2.case.dart';
import 'cases/started-count.4.7.case.dart';
import 'cases/take-anomaly.7.4.case.dart';
import 'cases/tap-live-card.5.4.case.dart';
import 'cases/tap-queued-card.5.3.case.dart';
import 'cases/tap-told-card.5.5.case.dart';

final logicCases = <RequirementCase>[
  appDeclarations_8_4,
  audienceDescriptors_1_5,
  countdownTone_2_8,
  jokeFields_1_1,
  laughEventFields_6_3,
  manualProvenance_5_7,
  noLaughScoresOnStage_4_6,
  oneCaptureClock_6_4,
  plannedLength_1_4,
  segmentModeAvailability_5_2,
  setOrder_1_3,
  setupSpans_1_2,
  startedCount_4_7,
  takeAnomaly_7_4,
  tapLiveCard_5_4,
  tapQueuedCard_5_3,
  tapToldCard_5_5,
];
