// GENERATED by dev/requirements/gate/coverage-gate.mjs --write. Do not edit.
// Swift cannot discover case files at runtime, so this list is what the runner
// executes; the gate fails when it and cases/ disagree.

enum LogicManifest {
    static let cases: [RequirementCase] = [
        appDeclarations_8_4,
        audienceDescriptors_1_5,
        countdownTone_2_8,
        jokeFields_1_1,
        laughEventFields_6_3,
        manualProvenance_5_7,
        noLaughScoresOnStage_4_6,
        oneCaptureClock_6_4,
        plannedLength_1_4,
        segmentModeAvailability_5_2,
        setOrder_1_3,
        setupSpans_1_2,
        startedCount_4_7,
        takeAnomaly_7_4,
        tapLiveCard_5_4,
        tapQueuedCard_5_3,
        tapToldCard_5_5,
    ]
}
