// GENERATED by dev/requirements/gate/coverage-gate.mjs --write. Do not edit.
// Swift cannot discover case files at runtime, so this list is what the runner
// executes; the gate fails when it and cases/ disagree.

enum LogicManifest {
    static let cases: [RequirementCase] = [
        appDeclarations_6_4,
        audienceDescriptors_1_5,
        countdownTone_2_9,
        jokeFields_1_1,
        laughEventFields_4_3,
        manualProvenance_3_6,
        noLaughScoresOnStage_2_7,
        oneCaptureClock_4_4,
        plannedLength_1_4,
        segmentModeAvailability_2_13,
        setOrder_1_3,
        setupSpans_1_2,
        startedCount_3_5,
        takeAnomaly_5_4,
        tapLiveCard_3_2,
        tapQueuedCard_3_1,
        tapToldCard_3_3,
    ]
}
