// GENERATED by dev/requirements/gate/coverage-gate.mjs --write. Do not edit.
// Dart cannot discover case files at runtime, so this list is what the runner
// executes; the gate fails when it and cases/ disagree.

import '../shared/requirement_case.dart';
import 'cases/working-the-set.9.1.case.dart';

final sagaCases = <RequirementCase>[
  workingTheSet_9_1,
];
