// GENERATED by dev/requirements/gate/coverage-gate.mjs --write. Do not edit.
// Swift cannot discover case files at runtime, so this list is what the runner
// executes; the gate fails when it and cases/ disagree.

enum BehaviorManifest {
    static let cases: [RequirementCase] = []
}
