// GENERATED by dev/requirements/gate/coverage-gate.mjs --write. Do not edit.
// Dart cannot discover case files at runtime, so this list is what the runner
// executes; the gate fails when it and cases/ disagree.

import '../shared/requirement_case.dart';
import 'cases/continuous-recording.6.1.case.dart';
import 'cases/interruption-resumes.6.6.case.dart';
import 'cases/library-survives-relaunch.1.6.case.dart';
import 'cases/recording-location.6.2.case.dart';
import 'cases/tap-on-capture-clock.5.6.case.dart';

final behaviorCases = <RequirementCase>[
  continuousRecording_6_1,
  interruptionResumes_6_6,
  librarySurvivesRelaunch_1_6,
  recordingLocation_6_2,
  tapOnCaptureClock_5_6,
];
