// GENERATED by dev/requirements/gate/coverage-gate.mjs --write. Do not edit.
// Swift cannot discover case files at runtime, so this list is what the runner
// executes; the gate fails when it and cases/ disagree.

enum BehaviorManifest {
    static let cases: [RequirementCase] = [
        continuousRecording_6_1,
        interruptionResumes_6_6,
        librarySurvivesRelaunch_1_6,
        recordingLocation_6_2,
        tapOnCaptureClock_5_6,
    ]
}
